<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='../../../../../../../../../../../test.xsl'?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM '../../../../../../../../../../../test.dtd'>
<!--
-->
<Test
    ID="Exception3"
        date-of-creation="2005-09-06"
        timeout="1">
        
        
        <Description>
            Jitrino hlo test.
            Tests method inlining.
            Tests that that it's ok to cath exception in inlined method, 
            throw it again, and catch in caller method.
        </Description>
        
        <Keyword name="functional"/>
        <Keyword name="hlo"/>
        
        <Source name="Exception3.java"/>
        <Runner ID="Runtime">
            <Param name="toRun" value="org.apache.harmony.test.func.jit.HLO.inline.Exception.Exception3.Exception3">
            </Param>
        </Runner>
</Test>
